site_name: Kotlin Agentic Framework
nav:
  - Documentation:
      - Overview: index.md
      - Simple API:
          - Getting started: simple-api-getting-started.md
          - Configuration options: simple-api-configuration.md
          - Available tools: simple-api-available-tools.md
      - AI Agent:
          - Getting started: ai-agent-getting-started.md
          - Configuration options: ai-agent-configuration.md
      - Stages And History: stagesAndHistory.md
      - Graph Nodes: graphNodes.md
      - Creating Tools: customTool.md
      - Handling Agent Events: eventHandler.md
      - Streaming API: streamingApi.md
      - Advanced Usage:
          - Structured Data: structuredData.md
          - Custom Nodes: customNodes.md
          - Custom Strategy Graphs: customGraphs.md
          - LLM Sessions and History: sessions.md
          - Features:
              - Tracing: tracingFeature.md
              - Memory: memoryFeature.md
      - Testing: testing.md
  - API reference: api-reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
  color_mode: light
  nav_style: light
  user_color_mode_toggle: true
  palette:
    - scheme: default
      primary: black
      accent: blue