site_name: Kotlin AI agents
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Basic Usage:
      - Creating Custom Tools: customTool.md
      - Handling Agent Events: eventHandler.md
      - Graph Nodes: nodes_library.md
      - Custom Graph Nodes: customNodes.md
      - Stages And History: stagesAndHistory.md
      - Streaming API: streamingApi.md
  - Advanced Usage:
      - Writing custom graphs: customGraphs.md
      - LLM Sessions and History: sessions.md
      - Structured Data: structuredData.md
theme:
  name: mkdocs
  favicon: images/favicon.ico
  color_mode: dark
  nav_style: dark
  user_color_mode_toggle: true