site_name: Kotlin AI agents
nav:
  - Home: index.md
  - Getting Started:
      - Simple API Quickstart: quickstart.md
      - Graph Nodes: nodes_library.md
  - Advanced Usage:
      - Creating Custom Tools: customTool.md
      - Handling Agent Events: eventHandler.md

theme:
  name: mkdocs
  color_mode: dark
  nav_style: dark
  user_color_mode_toggle: true