site_name: Koog
nav:
  - Documentation:
      - Overview: index.md
      - Key concepts: key-concepts.md
      - Examples: examples.md
      - Prompt API: prompt-api.md
      - Simple API:
          - Getting started: simple-api-getting-started.md
          - Configuration options: simple-api-configuration.md
          - Available tools: simple-api-available-tools.md
      - AI Agent:
          - Getting started: ai-agent-getting-started.md
      - Tools:
        - Tools declaration: tools-annotations.md
        - Advanced implementation: tools.md
      - Agent events: agent-events.md
      - Custom strategy graphs: custom-strategy-graphs.md
      - Pre-defined nodes and components: nodes-and-components.md
      - History compression: history-compression.md
      - Advanced usage:
          - Structured data: structured-data.md
          - Streaming API: streaming-api.md
          - Custom nodes: custom-nodes.md
          - LLM sessions and manual history management: sessions.md
          - Subgraphs:
              - Overview: subgraphs-overview.md
              - Custom subgraphs: custom-subgraphs.md
          - Embeddings: embeddings.md
          - Features:
              - Overview: features-overview.md
              - Tracing: tracing.md
              - Memory: agent-memory.md
      - Testing: testing.md
  - API reference: https://api.koog.ai/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
  color_mode: light
  nav_style: light
  user_color_mode_toggle: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: blue
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: blue

copyright: Copyright © 2000-2025 JetBrains s.r.o.
