site_name: Kotlin AI agents
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Basic Usage:
      - Creating Custom Tools: customTool.md
      - Handling Agent Events: eventHandler.md
      - Graph Nodes: nodes_library.md
      - Custom Graph Nodes: customNodes.md
      - Stages And History: stagesAndHistory.md
      - Streaming API: streamingApi.md
  - Advanced Usage:
      - Writing custom graphs: customGraphs.md
      - LLM Sessions and History: sessions.md
      - Structured Data: structuredData.md
      - Tracing: tracingFeature.md
      - Memory: memoryFeature.md
  - Testing:
      - Overview: testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - content.code.copy
  color_mode: dark
  nav_style: dark
  user_color_mode_toggle: true
  palette:
    # Palette toggle for light mode
#    - scheme: default
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode