site_name: Kotlin AI agents
nav:
  - Home: index.md
  - Simple API Quickstart: quickstartSimpleApi.md
  - Kotlin AI Agent Quickstart: quickstartKotlinAgent.md
  - Basic Usage:
      - Stages And History: stagesAndHistory.md
      - Graph Nodes: graphNodes.md
      - Creating Tools: customTool.md
      - Handling Agent Events: eventHandler.md
      - Streaming API: streamingApi.md
  - Advanced Usage:
      - Structured Data: structuredData.md
      - Custom Nodes: customNodes.md
      - Custom Strategy Graphs: customGraphs.md
      - LLM Sessions and History: sessions.md
      - Features:
          - Tracing: tracingFeature.md
          - Memory: memoryFeature.md
  - Testing: testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - content.code.copy
  color_mode: dark
  nav_style: dark
  user_color_mode_toggle: true
  palette:
    - scheme: slate
      primary: black
      accent: deep orange