name: Verify Code Snippets
on: pull_request

jobs:
  knit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - name: Generate and verify code examples
        run: |
          echo "Starting knit generation..."
          FILES_BEFORE_KNIT=$(find src/ -name "*.kt" 2>/dev/null | wc -l || echo "0")
          echo "Files before knit: $FILES_BEFORE_KNIT"
          
          ./gradlew knit
          
          FILES_AFTER_KNIT=$(find src/ -name "*.kt" 2>/dev/null | wc -l || echo "0")
          echo "Files after knit: $FILES_AFTER_KNIT"
          
          KNIT_GENERATED_FILES=$((FILES_AFTER_KNIT - FILES_BEFORE_KNIT))
          echo "Knit generated $KNIT_GENERATED_FILES files"
          
          echo "Starting build..."
          ./gradlew build